NDefines.NGraphics.BORDER_COLOR_DEMILITARIZED_R = 0.09
NDefines.NGraphics.BORDER_COLOR_DEMILITARIZED_G = 1.0
NDefines.NGraphics.BORDER_COLOR_DEMILITARIZED_B = 0.2
NDefines.NGraphics.BORDER_COLOR_DEMILITARIZED_A = 0.9
NDefines.NGame.START_DATE = "1936.1.1.12"
NDefines.NGame.END_DATE = "2188.1.1.12"
NDefines.NResistance.INITIAL_HISTORY_RESISTANCE = 20
NDefines.NResistance.INITIAL_HISTORY_COMPLIANCE = 10